services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: poker_backend
    environment:
      - PORT=3030
      - API_URL=http://localhost:3030
      - UI_URL=http://localhost:4173
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: poker_frontend
    environment:
      - VITE_PORT=80
      - VITE_UI_URL=http://localhost:80
      - VITE_API_URL=http://localhost:3030
    ports:
      - "4173:80"
    volumes:
      - ./client:/usr/src/app
